var state_2016 = 
[
    ['IN-TN','Tamil Nadu',1.01,'Normal'],
    ['IN-AP','Andhra Pradesh & Telangana',1.44,'Moderate'],
    ['IN-AR','Arunachal Pradesh',0.42,'Normal'],
    ['IN-AS','Assam',1.35,'Moderate'],
    ['IN-BR','Bihar',0.92,'Normal'],
    ['IN-CT','Chhattisgar',	1.1,'Normal'],
    ['IN-GA','Goa',0.08,'Normal'],
    ['IN-GJ','Gujarat',0.81,'Normal'],
    ['IN-HR','Haryana',0.59,'Normal'],
    ['IN-HP','Himachal Pradesh',1.26,'Moderate'],
    ['IN-JK','Jammu and Kashmir',1.03,'Normal'],
    ['IN-JH','Jharkhand',1.01,'Normal'],
    ['IN-KA','Karnataka',1.04,'Normal'],
    ['IN-KL','Kerala',1.12,'Normal'],
    ['IN-MP','Madhya Pradesh',0.98,'Normal'],
    ['IN-MH','Maharashtra',1.02,'Normal'],
    ['IN-MN','Manipur',0.95,'Normal'],
    ['IN-ML','Meghalaya',0.87,'Normal'],
    ['IN-MZ','Mizoram',0.76,'Normal'],
    ['IN-OR','Odisha',0.87,'Normal'],
    ['IN-PB','Punjab',1.07,'Normal'],
    ['IN-RJ','Rajasthan',1.38,'Moderate'],
    ['IN-TR','Tripura',1.15,'Normal'],
    ['IN-UP','Uttar Pradesh',1.04,'Normal'],
    ['IN-UT','Uttarakhand',0.97,'Normal'],
    ['IN-WB','West Bengal',2.13,'Moderate']
]
var state_2017 = 
[
    ['IN-TN','TAMIL NADU',0.99, "Normal"], 
    ['IN-AP','Andhra Pradesh & Telangana',1.42, "Moderate"], 
    ['IN-AR','Arunachal Pradesh',0.58, "Normal"], 
    ['IN-AS','Assam',1.21, "Moderate"], 
    ['IN-BR','Bihar',0.90, "Normal"], 
    ['IN-CT','Chhattisgarh',1.07, "Normal"], 
    ['IN-GA','Goa',0.14, "Normal"], 
    ['IN-GJ','Gujarat',0.90, "Normal"], 
    ['IN-HR','Haryana',0.48, "Normal"], 
    ['IN-HP','Himachal Pradesh',1.02, "Normal"], 
    ['IN-JK','Jammu and Kashmir',0.96, "Normal"], 
    ['IN-JH','Jharkhand',0.89, "Normal"], 
    ['IN-KA','Karnataka',0.81, "Normal"], 
    ['IN-KL','Kerala',1.15, "Normal"], 
    ['IN-MP','Madhya Pradesh',0.96, "Normal"], 
    ['IN-MH','Maharashtra',0.96, "Normal"], 
    ['IN-MN','Manipur',0.95, "Normal"], 
    ['IN-ML','Meghalaya',0.99, "Normal"], 
    ['IN-MZ','Mizoram',0.75, "Normal"], 
    ['IN-OR','Odisha',0.85, "Normal"], 
    ['IN-PB','Punjab',1.07, "Normal"], 
    ['IN-RJ','Rajasthan',1.32, "Moderate"], 
    ['IN-TR','Tripura',1.00, "Normal"], 
    ['IN-UP','Uttar Pradesh',1.00, "Normal"], 
    ['IN-UT','Uttarakhand',1.17, "Normal"], 
    ['IN-WB','West Bengal',2.47, "Moderate"] 
]
var state_2018 = 
[
	['IN-TN','Tamil Nadu',0.99,'Normal'],
	['IN-AP','Andhra Pradesh & Telangana',1.73,'Moderate'],
	['IN-AR','Arunachal Pradesh',0.61,'Normal'],
	['IN-AS','Assam',1.31,'Moderate'],
	['IN-BR','Bihar',0.95,'Normal'],
	['IN-CT','Chhattisgar',1.21,'Moderate'],
	['IN-GA','Goa',0.01,'Normal'],
	['IN-GJ','Gujarat',0.78,'Normal'],
	['IN-HR','Haryana',0.52,'Normal'],
	['IN-HP','Himachal Pradesh',1.42,'Moderate'],
	['IN-JK','Jammu and Kashmir',0.91,'Normal'],
	['IN-JH','Jharkhand',0.92,'Normal'],
	['IN-KA','Karnataka',0.86,'Normal'],
	['IN-KL','Kerala',1.22,'Moderate'],
	['IN-MP','Madhya Pradesh',0.98,'Normal'],
	['IN-MH','Maharashtra',1.04,'Normal'],
	['IN-MN','Manipur',1.11,'Normal'],
	['IN-ML','Meghalaya',0.79,'Normal'],
	['IN-MZ','Mizoram',1.21,'Moderate'],
	['IN-OR','Odisha',0.81,'Normal'],
	['IN-PB','Punjab',1.02,'Normal'],
	['IN-RJ','Rajasthan',1.42,'Moderate'],
	['IN-TR','Tripura',1.11,'Normal'],
	['IN-UP','Uttar Pradesh',1.03,'Normal'],
	['IN-UT','Uttarakhand',0.97,'Normal'],
	['IN-WB','West Bengal',2.45,'Critical']
]
