state_list = [ 
    {  
       "id":1,
       "state_name":"TAMIL NADU",
       "state_code":"IN-TN",
       "population":"72.1 Million",
       "population_urban":"37.2 Million",
       "population_rural":"34.92 Million",
       "literacy_rate":"80.09",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"17",
       "birth_rate":"16.6",
       "death_rate":"6.4",
       "immunization":"70",
       "state_gdp":"4520.63 billion",
       "bank_branches":10487,
       "capital":"Chennai",
       "area":"130,058 KM Sq",
       "hdi":"0.694",
       "sex_ration":"996",
       "sanitation":"100 %",
       "life_expectancy":72
    },
    {  
       "id":2,
       "state_name":"Andhra Pradesh",
       "state_code":"IN-AP",
       "population":"84 Million",
       "population_urban":"28.219",
       "population_rural":"56.362",
       "literacy_rate":"67.02",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"34",
       "birth_rate":"11.7",
       "death_rate":"6.8",
       "immunization":"65",
       "state_gdp":"4901.3409 Billions",
       "bank_branches":6839,
       "capital":"Hyderabad (Proposed Capital: Amaravati)",
       "area":"162968 KM Sq",
       "hdi":"0.627",
       "sex_ration":"993",
       "sanitation":"100%",
       "life_expectancy":69
    },
    {  
       "id":3,
       "state_name":"Arunachal Pradesh",
       "state_code":"IN-AR",
       "population":"1 Million",
       "population_urban":"0.317 Million",
       "population_rural":"1.066 Million",
       "literacy_rate":"65.39",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"36",
       "birth_rate":"16.4",
       "death_rate":"6.2",
       "immunization":"38.2",
       "state_gdp":"166.6248 Billion",
       "bank_branches":151,
       "capital":"Itanagar",
       "area":"83743 KM Sq",
       "hdi":"0.661",
       "sex_ration":"938",
       "sanitation":"100%",
       "life_expectancy":null
    },
    {  
       "id":4,
       "state_name":"Assam",
       "state_code":"IN-AS",
       "population":"31 Million",
       "population_urban":"4.399 Million",
       "population_rural":"26.807 Million",
       "literacy_rate":"72.19",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"44",
       "birth_rate":"18.9",
       "death_rate":"6.7",
       "immunization":"47",
       "state_gdp":"17892.964 Billion",
       "bank_branches":2306,
       "capital":"Dispur",
       "area":"78438 KM Sq",
       "hdi":"0.593",
       "sex_ration":"958",
       "sanitation":"97%",
       "life_expectancy":65
    },
    {  
       "id":5,
       "state_name":"Bihar",
       "state_code":"IN-BR",
       "population":"104 Million",
       "population_urban":"11.758 Million",
       "population_rural":"92.341 Million",
       "literacy_rate":"61.8",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"38",
       "birth_rate":"21.7",
       "death_rate":"6",
       "immunization":"62",
       "state_gdp":"30056.609 Billion",
       "bank_branches":6602,
       "capital":"Patna",
       "area":"94163 KM Sq",
       "hdi":"0.551",
       "sex_ration":"918",
       "sanitation":"76%",
       "life_expectancy":69
    },
    {  
       "id":6,
       "state_name":"Chhattisgarh",
       "state_code":"IN-CT",
       "population":"25 Million",
       "population_urban":"5.937 Million",
       "population_rural":"19.608 Million",
       "literacy_rate":"70.28",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"39",
       "birth_rate":"13.9",
       "death_rate":"7.4",
       "immunization":"76",
       "state_gdp":"20901.172 Billion",
       "bank_branches":2443,
       "capital":"Raipur",
       "area":"135191 KM Sq",
       "hdi":"0.586",
       "sex_ration":"991",
       "sanitation":"100%",
       "life_expectancy":65
    },
    {  
       "id":7,
       "state_name":"Goa",
       "state_code":"IN-GA",
       "population":"1 Million",
       "population_urban":"0.907 Million",
       "population_rural":"0.552 Million",
       "literacy_rate":"88.7",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"8",
       "birth_rate":"15.5",
       "death_rate":"6.7",
       "immunization":"88",
       "state_gdp":"4471.728 Billion",
       "bank_branches":686,
       "capital":"Panaji",
       "area":"3702 KM Sq",
       "hdi":"0.763",
       "sex_ration":"973",
       "sanitation":"76%",
       "life_expectancy":-1
    },
    {  
       "id":8,
       "state_name":"Gujarat",
       "state_code":"IN-GJ",
       "population":"60 Million",
       "population_urban":"25.745 Million",
       "population_rural":"34.695 Million",
       "literacy_rate":"78.03",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"30",
       "birth_rate":"12.9",
       "death_rate":"6.1",
       "immunization":"50.4",
       "state_gdp":"89466.723 Billion",
       "bank_branches":7697,
       "capital":"Gandhinagar",
       "area":"196024 KM Sq",
       "hdi":"0.651",
       "sex_ration":"919",
       "sanitation":"100%",
       "life_expectancy":69
    },
    {  
       "id":9,
       "state_name":"Haryana",
       "state_code":"IN-HR",
       "population":"25 Million",
       "population_urban":"8.842 Million",
       "population_rural":"16.509 Million",
       "literacy_rate":"75.55",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"33",
       "birth_rate":"20.1",
       "death_rate":"5.9",
       "immunization":"62",
       "state_gdp":"39964.594 Billion",
       "bank_branches":4762,
       "capital":"Chandigarh",
       "area":"44212 KM Sq",
       "hdi":"0.687",
       "sex_ration":"879",
       "sanitation":"100%",
       "life_expectancy":69
    },
    {  
       "id":10,
       "state_name":"Himachal Pradesh",
       "state_code":"IN-HP",
       "population":"6 Million",
       "population_urban":"0.689 Million",
       "population_rural":"6.176 Million",
       "literacy_rate":"82.8",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"25",
       "birth_rate":"20.7",
       "death_rate":"6.8",
       "immunization":"70",
       "state_gdp":"9720.666 Billion",
       "bank_branches":1542,
       "capital":"Shimla",
       "area":"55673 KM Sq",
       "hdi":"0.706",
       "sex_ration":"972",
       "sanitation":"100%",
       "life_expectancy":72
    },
    {  
       "id":11,
       "state_name":"Jammu and Kashmir",
       "state_code":"IN-JK",
       "population":"12 Million",
       "population_urban":"3.433 Million",
       "population_rural":"9.108 Million",
       "literacy_rate":"67.16",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"24",
       "birth_rate":"16",
       "death_rate":"5",
       "immunization":"75",
       "state_gdp":"9728.927 Billion",
       "bank_branches":1741,
       "capital":"Srinagar",
       "area":"222236 KM Sq",
       "hdi":"0.675",
       "sex_ration":"889",
       "sanitation":"100%",
       "life_expectancy":73
    },
    {  
       "id":12,
       "state_name":"Jharkhand",
       "state_code":"IN-JH",
       "population":"32 Million",
       "population_urban":"7.933 Million",
       "population_rural":"25.055 Million",
       "literacy_rate":"66.41",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"29",
       "birth_rate":"15.7",
       "death_rate":"5.5",
       "immunization":"61.9",
       "state_gdp":"19753.56 Billion",
       "bank_branches":2910,
       "capital":"Ranchi",
       "area":"79714 KM Sq",
       "hdi":"0.578",
       "sex_ration":"949",
       "sanitation":"100%",
       "life_expectancy":67
    },
    {  
       "id":13,
       "state_name":"Karnataka",
       "state_code":"IN-KA",
       "population":"61 Million",
       "population_urban":"23.626 Million",
       "population_rural":"37.469 Million",
       "literacy_rate":"75.37",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"24",
       "birth_rate":"22.9",
       "death_rate":"6.7",
       "immunization":"62.6",
       "state_gdp":"81349.741Billion",
       "bank_branches":10037,
       "capital":"Bengaluru",
       "area":"191791 KM Sq",
       "hdi":"0.662",
       "sex_ration":"973",
       "sanitation":"100%",
       "life_expectancy":69
    },
    {  
       "id":14,
       "state_name":"Kerala",
       "state_code":"IN-KL",
       "population":"33 Million",
       "population_urban":"15.935 Million",
       "population_rural":"17.471 Million",
       "literacy_rate":"94",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"10",
       "birth_rate":"17.6",
       "death_rate":"7.6",
       "immunization":"82",
       "state_gdp":"44769.237 Billion",
       "bank_branches":6452,
       "capital":"Thiruvananthapuram",
       "area":"38863 KM Sq",
       "hdi":"0.77",
       "sex_ration":"1084",
       "sanitation":"100%",
       "life_expectancy":75
    },
    {  
       "id":15,
       "state_name":"Madhya Pradesh",
       "state_code":"IN-MP",
       "population":"72 Million",
       "population_urban":"20.069 Million",
       "population_rural":"52.557 Million",
       "literacy_rate":"69.32",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"47",
       "birth_rate":"18.9",
       "death_rate":"7.1",
       "immunization":"53.6",
       "state_gdp":"165977.605 Billion",
       "bank_branches":6411,
       "capital":"Bhopal",
       "area":"308350 KM Sq",
       "hdi":"0.577",
       "sex_ration":"931",
       "sanitation":"100%",
       "life_expectancy":65
    },
    {  
       "id":16,
       "state_name":"Maharashtra",
       "state_code":"IN-MH",
       "population":"112 Million",
       "population_urban":"50.818 Million",
       "population_rural":"61.556 Million",
       "literacy_rate":"82.34",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"19",
       "birth_rate":"25.1",
       "death_rate":"5.9",
       "immunization":"56",
       "state_gdp":"1585.639 Billion",
       "bank_branches":12392,
       "capital":"Mumbai",
       "area":"307713 KM Sq",
       "hdi":"0.683",
       "sex_ration":"929",
       "sanitation":"100%",
       "life_expectancy":72
    },
    {  
       "id":17,
       "state_name":"Manipur",
       "state_code":"IN-MN",
       "population":"2Million",
       "population_urban":"0.834 Million",
       "population_rural":"1.736 Million",
       "literacy_rate":"89.22",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"11",
       "birth_rate":"15.9",
       "death_rate":"4.5",
       "immunization":"66",
       "state_gdp":"2175.649 Billion",
       "bank_branches":159,
       "capital":"Imphal",
       "area":"22327 KM Sq",
       "hdi":"0.699",
       "sex_ration":"992",
       "sanitation":"100%",
       "life_expectancy":-1
    },
    {  
       "id":18,
       "state_name":"Meghalaya",
       "state_code":"IN-ML",
       "population":"2 Million",
       "population_urban":"0.595 Million",
       "population_rural":"2.371 Million",
       "literacy_rate":"74.43",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"39",
       "birth_rate":"12.9",
       "death_rate":"6.6",
       "immunization":"62",
       "state_gdp":"1248.773 Billion",
       "bank_branches":338,
       "capital":"Shillong",
       "area":"22429 KM Sq",
       "hdi":"0.648",
       "sex_ration":"989",
       "sanitation":"100%",
       "life_expectancy":-1
    },
    {  
       "id":19,
       "state_name":"Mizoram",
       "state_code":"IN-MZ",
       "population":"1 Million",
       "population_urban":"0.572 Million",
       "population_rural":"0.525 Million",
       "literacy_rate":"91.33",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"27",
       "birth_rate":"23.7",
       "death_rate":"4.2",
       "immunization":"51",
       "state_gdp":"1485.111 Billion",
       "bank_branches":186,
       "capital":"Aizawl",
       "area":"21081 KM Sq",
       "hdi":"0.697",
       "sex_ration":"976",
       "sanitation":"100%",
       "life_expectancy":-1
    },
    {  
       "id":20,
       "state_name":"Odisha",
       "state_code":"IN-OR",
       "population":"41Million",
       "population_urban":"7.004 Million",
       "population_rural":"34.971 Million",
       "literacy_rate":"72.89",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"44",
       "birth_rate":"14",
       "death_rate":"7.8",
       "immunization":"79",
       "state_gdp":"2003.237 Billion",
       "bank_branches":4748,
       "capital":"Bhubaneswar",
       "area":"155707 KM Sq",
       "hdi":"0.58",
       "sex_ration":"979",
       "sanitation":"67%",
       "life_expectancy":67
    },
    {  
       "id":21,
       "state_name":"Punjab",
       "state_code":"IN-PB",
       "population":"27.7 Million",
       "population_urban":"10.399 Million",
       "population_rural":"17.344 Million",
       "literacy_rate":"75.84",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"21",
       "birth_rate":"13.9",
       "death_rate":"6",
       "immunization":"89",
       "state_gdp":"55814.433 Billion",
       "bank_branches":6366,
       "capital":"Chandigarh",
       "area":"50362 KM Sq",
       "hdi":"0.706",
       "sex_ration":"895",
       "sanitation":"100%",
       "life_expectancy":72
    },
    {  
       "id":22,
       "state_name":"Rajasthan",
       "state_code":"IN-RJ",
       "population":"68.5 Million",
       "population_urban":"17.048 Million",
       "population_rural":"51.5 Million",
       "literacy_rate":"66.11",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"41",
       "birth_rate":"14.9",
       "death_rate":"6.1",
       "immunization":"55",
       "state_gdp":"1408.684 Billion",
       "bank_branches":7011,
       "capital":"Jaipur",
       "area":"342239 KM Sq",
       "hdi":"0.601",
       "sex_ration":"928",
       "sanitation":"100%",
       "life_expectancy":68
    },
    {  
       "id":23,
       "state_name":"Tripura",
       "state_code":"IN-TR",
       "population":"3.7 Million",
       "population_urban":"0.961 Million",
       "population_rural":"2.712 Million",
       "literacy_rate":"87.22",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"24",
       "birth_rate":"15",
       "death_rate":"6.1",
       "immunization":"55",
       "state_gdp":"2782.03 Billion",
       "bank_branches":442,
       "capital":"Agartala",
       "area":"10486 KM Sq",
       "hdi":"0.645",
       "sex_ration":"960",
       "sanitation":"88%",
       "life_expectancy":-1
    },
    {  
       "id":24,
       "state_name":"Uttar Pradesh",
       "state_code":"IN-UP",
       "population":"199.8 Million",
       "population_urban":"44.495 Million",
       "population_rural":"155.317Million",
       "literacy_rate":"67.68",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"43",
       "birth_rate":"17.5",
       "death_rate":"5.5",
       "immunization":"51",
       "state_gdp":"90164.491 Billion",
       "bank_branches":16774,
       "capital":"Lucknow",
       "area":"243290 KM Sq",
       "hdi":"0.566",
       "sex_ration":"912",
       "sanitation":"100%",
       "life_expectancy":65
    },
    {  
       "id":25,
       "state_name":"Uttarakhand",
       "state_code":"IN-UT",
       "population":"10.1 Million",
       "population_urban":"3.049 Million",
       "population_rural":"7.037 Million",
       "literacy_rate":"78.82",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"38",
       "birth_rate":"13.7",
       "death_rate":"6.9",
       "immunization":"58",
       "state_gdp":"15190.073 Billion",
       "bank_branches":2029,
       "capital":"Dehradun",
       "area":"53483 KM Sq",
       "hdi":"0.662",
       "sex_ration":"963",
       "sanitation":"100%",
       "life_expectancy":72
    },
    {  
       "id":26,
       "state_name":"West Bengal",
       "state_code":"IN-WB",
       "population":"91.3 Million",
       "population_urban":"29.093 Million",
       "population_rural":"62.183 Million",
       "literacy_rate":"76.26",
       "literacy_rate_male":null,
       "literacy_rate_female":null,
       "infant_mortality_rate":"25",
       "birth_rate":"26.2",
       "death_rate":"6.7",
       "immunization":"84",
       "state_gdp":"0 Billion",
       "bank_branches":7903,
       "capital":"Kolkata",
       "area":"88752 KM Sq",
       "hdi":"0.62",
       "sex_ration":"950",
       "sanitation":"96%",
       "life_expectancy":71
    }
 ]
